{
 "title": "Real-Time Fraud Detection Dashboard",
 "time": { "from": "2026-09-04T15:08:01.267Z", "to": "2026-09-04T15:18:35.644Z" },
 "panels": [
  {
   "title": "Total Fraud Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT COUNT(*) AS total_alerts\nFROM fraud_alerts;\n"
    }
   ]
  },
  {
   "title": "Fraud Amount",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT SUM(amount) AS fraud_amount\nFROM fraud_alerts;"
    }
   ]
  },
  {
   "title": "Fraud Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT COUNT(*) AS fraud_alerts\nFROM fraud_detection.fraud_alerts;"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 11, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT COUNT(*) AS total_transactions\nFROM fraud_detection.transactions;\n"
    }
   ]
  },
  {
   "title": "Fraud Alert Volume",
   "type": "stat",
   "description": "Total number of fraud alerts generated by the real-time fraud detection pipeline.",
   "gridPos": { "h": 3, "w": 23, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT COUNT(*) AS alert_count\nFROM fraud_detection.fraud_alerts;\n"
    }
   ]
  },
  {
   "title": "Transaction velocity",
   "type": "timeseries",
   "description": "Use your transaction table and count transactions over time. If your transaction table has a timestamp column, use that as the time field",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "SELECT event_time, amount\nFROM fraud_detection.fraud_alerts"
    }
   ]
  },
  {
   "title": "Fraud Alert Amount Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 9 },
   "targets": [
    {
     "target": "SELECT event_time, amount\nFROM fraud_detection.fraud_alerts\nLIMIT 20\n"
    }
   ]
  },
  {
   "title": "Fraud Alert Velocity",
   "type": "timeseries",
   "description": "this will show individual alert events, not a true \"alerts per minute\" rate. For a proper velocity metric such as 10 alerts/min → 25 alerts/min → 40 alerts/min",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "target": "SELECT event_time, amount\nFROM fraud_detection.fraud_alerts\n"
    }
   ]
  },
  {
   "title": "Transaction Velocity",
   "type": "timeseries",
   "description": "Measures transaction activity over time to identify sudden increases or unusual transaction patterns. This helps monitor transaction velocity and detect potentially suspicious activity in real time.",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 17 },
   "targets": [
    {
     "target": "SELECT event_time, amount\nFROM fraud_detection.fraud_alerts;"
    }
   ]
  }
 ]
}